gnn:
  SEED: 42

  NUM_GRAPHS: 500
  NODE_CHOICES: [9, 10, 11]

  EDGE_P_MIN: 0.2
  EDGE_P_MAX: 0.9

  WEIGHT_UNIFORM_RANGE: [0, 1.0]

  WEIGHTED_RATIO: 0.95

  NODE_FEATURE_DIM: 4

  EMBEDDING_DIM: 500
  HIDDEN_DIM: 128
  NUM_LAYERS: 3

  EPOCHS: 20
  LR: 1e-3
  WEIGHT_DECAY: 1e-4
  BATCH_SIZE: 32

  TEMPERATURE: 0.2

  MODEL_PATH: "models/gnn_graph_encoder_contrastive.pt"

feather:
  FEATHER_ORDER: 5
  FEATHER_EVAL_POINTS: 25
  FEATHER_THETA_MAX: 2.5
  FEATHER_POOLING: "mean"

netlsd:
  SCALE_STEPS: 500
  APPROX: 50